-- Generated by HyprMod

-- Monitors
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "preferred",
    position = "auto",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2880x1920@60.00Hz",
    position = "-380x380",
    scale = 2,
    bitdepth = 10,
    cm = "srgb",
})
