general {
    lock_cmd = /home/tirbofish/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = brightnessctl -sd *::kbd_backlight set 0
    on-resume = brightnessctl -rd *::kbd_backlight
}

listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
