wireplumber.profiles = {
  main = {
    hooks.default-nodes.force-configured = required
  }
}

wireplumber.components = [
  {
    name = force-configured-default.lua
    type = script/lua
    provides = hooks.default-nodes.force-configured
    requires = [ metadata.default ]
  }
]
